### ISSUE TITLE
Configuración-->ABM Lista de Valores: al crear una lista para todas las empresas, falla y no muestra sus valores

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#103]
Ambiente test - v2.0.15.4.1

**Descripción**
Estando en el perfil de superadmin, al crear una Lista de valores con la opción para Todas las Empresas el sistema no la reconoce y obliga al usuario a seleccionar una empresa específica. Lo correspondiente sería que permita usar los valores de la lista en Todas Las empresas como lo especifica el campo

![image](https://user-images.githubusercontent.com/88331456/175561100-d299b559-69e4-48db-9005-c33980565555.png)

(Activar el audio del video)

https://user-images.githubusercontent.com/88331456/175560206-ffaa6887-c356-4a84-b80f-83f2e4b0f90f.mp4

**Pasos a seguir**
1. En Configuración
2. Clic en ABM Lista de Valores
3. Clic en el botón "Agregar"
4. Completar los campos obligatorios
5. clic en el botón "Confirmar"

**Comment by focafunk** [comment]
En mi opinion esta bien como funciona, debe tener cada empresa una lista de tipos de trabajo distinta, entiendo entonces que no es un bug
