### ISSUE TITLE
Bandeja "Mis Tareas": no muestra los datos de la Tarea o Pedido de trabajo / materiales

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#104]
Ambiente test - v2.0.15.4.1

**Descripción**
Al guardar un Pedido de Trabajo el sistema enlista el mismo en la Bandeja de tareas pero no muestra la información: Descripción, Nro. de Pedido, Estado, Fecha y Justificación. Lo correspondiente es visualizar esos datos sin dar clic en la tarea para saber de qué se trata

![image](https://user-images.githubusercontent.com/88331456/175951164-d8690703-7d67-4b59-9553-339de797c887.png)

**Pasos a seguir**
1. En Tareas
2. Clic en "Pedidos trabajo"
3. Clic en el botón Agregar
4. Completar los datos obligatorios
5. Clic en el botón Guardar
6. Clic en el botón Mis Tareas

**Comment by focafunk** [comment]
Pareceria que (no se por que) son datos corruptos con los que esta probando. Acabo de generar 1 de 0 y si se ve, quizas alguien desconfiguro algo sin querer justo cuando probaron
![image](https://user-images.githubusercontent.com/38109047/176680611-60bf797b-b681-4103-9f0d-dde9db694ca8.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.0.16
