### ISSUE TITLE
Dnato-->Error de configuración al asignar una Tarea planificada

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#117]
Ambiente - v2.0.18 

**Descripción**
Cuando un nuevo usuario quiere tomar la tarea planificada asignada por el supervisor, el sistema no avanza con el proceso y el botón "tomar tarea" pierde funcionalidad (relacionado con issue [de tareas](https://github.com/Trazalog/traz-comp-tareasestandar/issues/72))
_(Rogelio explicó que es un error de configuración de permisos al crear nuevos usuarios)_

https://user-images.githubusercontent.com/88331456/181078702-20531518-57d4-46da-acdb-f299b7d81daf.mp4

_Para realizar esta prueba se usó:_ 
user: nadiaferro@gmail.com
password: 12345

**Pasos a seguir**  
1. Bandeja tareas al seleccionar una tarea planificada (con el usuario Nadia Ferro)
2. Clic en el botón "tomar tarea"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v2.1.5 
El error se debía a que el usuario no tenía asignado los permisos.
