### ISSUE TITLE
Menú-->agregar multiniveles 

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#135]
v 2.1.1

Descripción:
Permitir que el menú tenga multiniveles. 
Ej: El módulo Producción debería contener en nivel 1 a los submódulos Reportes y Logística. 

![image](https://user-images.githubusercontent.com/87376576/183435959-7ed15b17-4bd9-4e99-81a6-6fafa16f4e61.png)

**Comment by floto-trazalog** [comment]
Solucionado antes de v2.1.8
