### ISSUE TITLE
Configuraciones-->ABM Lista de valores: al agregar una lista no figura en el select

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#139]
Ambiente test - v2.1.1

**Descripción**
Al agregar la lista de valores de estados de Argentina el sistema no registra ese listado en el select de... 

![image](https://user-images.githubusercontent.com/88331456/183489707-56b537d9-420b-4655-ae0e-bac456c6ba91.png)

... Gestión de Empresas-->Agregar empresa, que se aprecia en la imagen

![image](https://user-images.githubusercontent.com/88331456/183492405-47aa3190-8fda-4efb-ae90-db1d4b951796.png)

**Pasos para reproducir**
1. En Configuración
2. Clic en ABM Lista de valores
3. Completar  campos obligatorios
4. Clic en el botón "Confirmar"
5. Y luego, revisar en "Dnato-->Gestión de empresas-->Agregar empresa"
6. Seleccionar el país "Argentina"
7. Seleccionar el "Estado"

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.4.1

**Comment by aalfaro-trazalog** [comment]
Funcionando en: PRD v2.
Dnato Versión v1.2.10
