### ISSUE TITLE
Configuración--> Establecimientos: agregar encargado de depósito

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#160]
Descripción:

En Configuración--> Establecimientos--> Depósitos

![image](https://user-images.githubusercontent.com/87376576/186183845-8b1fc0fc-2c8f-46fb-8092-1ccec182b6ad.png)

Agregar un campo tipo select para asignar el responsable del depósito, que traiga el nombre de los usuarios por empresa.

![image](https://user-images.githubusercontent.com/87376576/186183451-c9e6fc9c-bdf3-4f62-bf02-398cc591b950.png)

Este ticket impacta en las issue:

-  https://github.com/Trazalog/traz-comp-almacenes/issues/91 
- https://github.com/Trazalog/traz-tools/issues/161
- https://github.com/Trazalog/traz-comp-almacenes/issues/93

**Comment by floto-trazalog** [comment]
Soucionado en v2.1.6.4
