### ISSUE TITLE
Configuración--> Establecimientos: agregar acciones para editar y ver detalles de depósito

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#161]
Descripción:

1) En Configuración--> Establecimientos--> Depósitos

![image](https://user-images.githubusercontent.com/87376576/186184892-352694cb-9d1a-4c86-8586-767d702f5121.png)

2) En Lista de establecimientos, modificar acciones: agregar editar y ver detalles, actualizar iconos
![image](https://user-images.githubusercontent.com/87376576/186186039-01b65879-ff20-4f20-aa58-f041b738f53c.png)

**Comment by floto-trazalog** [comment]
Casi solucionado:  v2.1.4.6 

Se recomienda establecer los íconos pedidos en el issue puesto que es importante mantener esta consistencia de los botones en todo el sistema

![image](https://user-images.githubusercontent.com/88331456/189761733-8a4c213d-3bc7-48fd-8c03-de62040d70cd.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.8.8
