### ISSUE TITLE
Dnato--> Editar perfil: agregar opción de poder cambiar la foto de usuario

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#166]
Descripción:
Agregar campo que permita subir una nueva imagen de perfil para el usuario.

Agregar previsualizador de imagen.

![image](https://user-images.githubusercontent.com/87376576/188733006-70bda0f2-8acd-4a32-8ffd-4edd2e04d6bb.png)

**Comment by floto-trazalog** [comment]
Con detalles por mejorar.
 Solucionado en Dnato - v1.2.14
