### ISSUE TITLE
Configuración-->ABM Transportistas: en la pantalla no refleja lo que indica la base de datos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#167]
Ambiente test - v2.1.4.5

**Descripción**
Se detectó que la pantalla no está reflejando lo que muestra la base de datos, por lo tanto es importante homogeneizar los datos.
Además, es necesario maquetar la vista de la pantalla con los datos correctos:

- Agregar campos no requeridos, como: Teléfono, email.

- Quitar obligatoriedad al campo CUIT.

**Pasos a reproducir** 
1. En Configuración
2. ABM Transportistas

**Comment by gramos-trazalog** [comment]
https://drive.google.com/file/d/1FhYkxn0KdCXmFB7ONTLzoWCcyNNmdcQu/view

**Comment by floto-trazalog** [comment]
Solucionado en test - v2.1.7.6
