### ISSUE TITLE
ABM Recipientes: al eliminar recipiente se tilda la pantalla

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#179]
Ambiente PROD de ISOLA

Descripción:
Luego de eliminar el recipiente se tilda la pantalla

https://user-images.githubusercontent.com/87376576/187694519-ddc789f8-e641-49a6-a928-f89e5ec5da55.mp4

**Comment by gnicolia-trazalog** [comment]
Solucionado en V 2.2.18.1
