### ISSUE TITLE
Dnato--> Roles: Se duplican los usuarios

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#186]
v 2.1.4.5 Ambiente PROD

Descripción:
Cuando en un usuario se requiere asignar un rol especifico, el mismo se duplica e inclusive trae otro rol asociado:

![image](https://user-images.githubusercontent.com/87376576/194118118-4d72410f-676d-481d-b91a-949528dc9e4d.png)

**Comment by floto-trazalog** [comment]
Solucionado en Dnato - v1.2.14
