### ISSUE TITLE
Configuraciones-->ABM Transportistas: permite agregar un transportista con el cuit repetido

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#196]
Ambiente test - v2.1.9.2

**Descripción**
Al momento de guardar un transportista nuevo el sistema permite realizar el guardado con el mismo cuit de otro transportista ya ingresado y lo correcto sería que valide que el cuit ingresado sea único y no se repita.

![image](https://user-images.githubusercontent.com/88331456/202538867-383559f6-2d08-4a6b-a2b8-f5689c362acd.png)

_Video - activar audio_

https://github.com/Trazalog/traz-tools/assets/88331456/89d565e1-589a-4bbe-ac33-60d7606c43c2

**Comment by gnicolia-trazalog** [comment]
Solucionado en V 2.2.18.1
La prueba esta realizada desde un smartphone
