### ISSUE TITLE
Configuraciones-->Creación de recipientes: no guarda recipiente del tipo DEPÓSITO/PRODUCTIVO

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#212]
Ambiente Producción - v2.1.17

**Descripción:**
Al agregar un nuevo depósito/productivo el sistema no lo graba en la lista de registros de Recipientes

https://user-images.githubusercontent.com/88331456/218844739-92e70994-40d5-4a90-832a-1dce35fb6fdb.mp4

**Comment by gnicolia-trazalog** [comment]
Continua igual en V 2.2.18.1

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.9.1
