### ISSUE TITLE
SOPORTE-->Configuración-->Recetas: no agrega el 2do artículo

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#243]
Ambiente DEMO - v2.2.13

**Descripción**
que permita guardar el segundo artículo para poder guardar dicha receta

**Comment by jfernandez-trazalog** [comment]
Roge Sanchez.-

**Comment by floto-trazalog** [comment]
Solucionado (al actualizar versión) - v2.2.20
