### ISSUE TITLE
Reprecintado: Guardar resultado en una columna aparte

### ISSUE THREAD

**Issue by rodolfo-ruiz-rtools** [Trazalog/traz-tools#244]
1 - Generar una nueva columna en inspecciones para guardar el resultado de reprecintado, oy modifica el resultado de la inspección en PCC
2 - Al setear que la inspeccion de reprecintado NO es correcta, el acta debe contener los datos de los permisos de transito de reprecintado, hoy muestra los de PCC

**Comment by jfernandez-trazalog** [comment]
Gerardo Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado
