### ISSUE TITLE
Dnato: al agregar un nuevo menú, recupera el tag de html en el front 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#246]
Ambiente test - v3.7.8

**Descripción:**
En el menú, al agregar un nuevo módulo el sistema recupera un tag de html en el front. 
Es importante para la experiencia del usuario con la interfaz.

![image](https://github.com/user-attachments/assets/3df6b3cf-70ef-4b8d-9dda-b8c47a93ea48)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado.
