### ISSUE TITLE
SOPORTE>>TICA-->Mis Tareas: modificaciones en el cuadro de dialogo

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#250]
Ambiente Test - v2.3.11

**Descripción:**
1. En el título--> cambiar "Echo" por "Hecho"
2. En la descripción--> cambiar "Cancelo" por "Aprobó"

![image](https://github.com/user-attachments/assets/65620234-ad80-4d65-a5ed-d7086b15af9e)

**Pasos a reproducir:**
1. Previamente, crear un nuevo "Pedido de materiales"
2. Ir a "Mis Tareas", seleccionar la tarea **Aprobar pedido de materiales** del paso 1)
3. Dar clic en "Aprobar" y luego, en botón "Hecho"

**Comment by jfernandez-trazalog** [comment]
Rogelio Sanchez.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.9.1
