### ISSUE TITLE
ARMO-->Configuraciones-->ABM Lista de precios: al agregar nueva lista, que guarde el Nro de versión y la descripción

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#252]
Ambiente Test - v2.4.0

**Descripción:**
Al ingresar los datos para agregar una nueva lista de precios con versión inicial 1 e ingresar la **Descripción** de la misma y guardar la lista con los datos requeridos completos; en el listado de precios el sistema no recupera EL NRO DE VERSIÓN y tampoco, el DETALLE.
Se dejan evidencias probadas en el link
URL: http://10.142.0.16/test/traz-comp-dnato/main/login
user: jperez@prueba.com
pass: 12345

![image](https://github.com/user-attachments/assets/ab6f95bd-173f-45f2-983f-2006cb24bf9f)

![image](https://github.com/user-attachments/assets/f5c8f207-c376-42e2-af02-b5e63b0756d9)

**Pasos a reproducir:**
1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Clic en el botón "Agregar"
4. Completar los campos obligatorios y "Descripción de versión" 
5. Clic en el botón "Agregar"
6. Clic en el botón "Guardar"

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.1
