### ISSUE TITLE
ARMO-->Configuraciones-->ABM Lista de precios: al agregar nueva lista no valida el ingreso de los campos requeridos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#253]
Ambiente Test - v2.4.0

**Descripción:**
Al presionar el botón para agregar una nueva lista de precios y presionar el botón "Guardar" el sistema comienza una carga infinita en donde la pantalla no refresca. Y luego, al refrescar la página se observa que se ha guardado correctamente, cuando lo considerable es que valide al momento de guardar la lista y además, no grave el registro en el listado

Se dejan credenciales de las pruebas realizadas --> 
--> URL: http://10.142.0.16/test/traz-comp-dnato/main/login
user: [jperez@prueba.com](mailto:jperez@prueba.com)
pass: 12345

https://github.com/user-attachments/assets/15833b9a-9ee6-452b-ac8f-fce658a9a310

https://github.com/user-attachments/assets/66d4e360-a9f8-4d78-a60c-a20cf07bfbd6

https://github.com/user-attachments/assets/6361e798-551f-4b9c-9572-791aeae5ebd6

**Pasos a reproducir:**

1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Clic en el botón "Agregar"
4. Clic en el botón "Guardar"

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.2
