### ISSUE TITLE
ARMO-->Configuraciones-->ABM Lista de precios-->Botón "Ver": se mantienen los datos del listado anterior de articulos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#255]
Ambiente Test - v2.4.0

**Descripción:**
En el ABM Lista de precios, cuando se le da clic al botón "Ver" y luego se cierra el modal y se abre el "Ver" pero de otra lista se queda pegado el listado de articulos del primer modal.

_Más abajo se deja la evidencia (video)._

Se dejan credenciales de las pruebas realizadas -->
--> URL: http://10.142.0.16/test/traz-comp-dnato/main/login
user: [jperez@prueba.com](mailto:jperez@prueba.com)
pass: 12345

https://github.com/user-attachments/assets/38f5afc9-5404-4909-a78f-e0ac8ed8e9b2

**Pasos a reproducir:**

1. En el menú "Configuraciones"
2. Clic en ABM Lista de precios
3. Clic en el botón "Ver" de una lista
4. Clic en el botón "Cancelar"
5. Clic en el botón "Ver" de una lista diferente a la del paso (3)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.2
