### ISSUE TITLE
Configuraciones-->ABM Lista de precios: muestra un aviso de error 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#259]
Ambiente Test - v2.4.2

**Descripción:**
Al grabar una nueva lista muestra el cartel de error, pero la lista se guarda correctamente.
Se recomienda revisar si se presenta por algún fallo

https://github.com/user-attachments/assets/ddf63033-0763-4c7c-96b7-309083a70759

**Pasos a reproducir:**

1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Clic en el botón de acción "Nueva versión"
4. Completar los campos obligatorios
5. Clic en el botón "Agregar"
6. Clic en el botón "Guardar"

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.3
