### ISSUE TITLE
Configuraciones-->ABM Lista de precios: que los registros de la nueva versión sobrescriba la versión anterior en el registro

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#260]
Ambiente Test - v2.4.2

**Descripción:**
 **Crear nueva versión**
Al agregar una nueva versión se está generando un nuevo registro en el listado y lo correspondiente sería que el registro de versiones se actualice para que la nueva versión reemplace a la anterior

https://github.com/user-attachments/assets/1059daf3-a003-47c8-8196-bcade53edb39

**Resultado esperado:**
Que al agregar una nueva versión el sistema solo muestre la última versión, puesto que se encuentra el botón de acción "Versiones", o se podrñia filtrar para que solo muestre en pantalla las últimas versiones de cada lista de precios.

**Pasos a reproducir:**

1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Clic en el botón de acción "Nueva versión"
4. Seleccionar un "Artículo"
5. Clic en el botón "Agregar"
6. Clic en el botón "Guardar"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.3
