### ISSUE TITLE
Configuraciones-->ABM Lista de precios: aviso de error al agregar artículo 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#261]
Ambiente Test - v2.4.2

**Descripción:**

Cuando se quiere agregar una nueva versión el sistema imprime en pantalla un aviso de error al cargar el artículo, y de igual manera se guarda correctamente.
**Nota:** esto solo sucede cuando no se refresca la página, es decir, se aplican las acciones.

**Pasos a reproducir:**
1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Clic en el botón de acción "Nueva versión"
4. Seleccionar un "Artículo"
5. Clic en el botón "Agregar"

https://github.com/user-attachments/assets/dbea24ff-b2fb-482f-95e7-d11cd5df25c3

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
https://github.com/user-attachments/assets/3a6e5660-2a99-440b-ac1f-3d8cf426564f

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.5
