### ISSUE TITLE
Configuraciones-->ABM Lista de precios: falla al ingresar por primera vez a la interfaz

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#262]
Ambiente Test - v2.4.2

**Descripción:** 
_Título: El precalentamiento de la interfaz_ 
Al ingresar al sistema por primera vez, sin haber realizado acciones, dar clic en el botón de acción "crear nueva versión" e intentar agregar un nuevo artículo al listado se elimina automáticamente el listado de la versión anterior y se guarda el artículo agregado recientemente 

(activar audio)

https://github.com/user-attachments/assets/088d9bfe-c40c-4567-8eef-561461bf39bd

Luego, se oobserva que al agregar una nueva lista y después, crear versiones nuevas el sistema graba correctamente los datos. (activar audio)

https://github.com/user-attachments/assets/c51858b3-8817-43ef-add9-a6b59f65c6ad

**Pasos a reproducir:**

1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Elegir una lista de precios 
4. Clic en el botón de acción "Nueva versión"
5. Seleccionar un "Artículo"
Clic en el botón "Agregar"

**Nota:** En caso de tener inconvenientes para ver los videos, se deja un enlace con el [video completo](https://drive.google.com/file/d/1Ey5LdQipNhhAk8ZVLmqFtrObBFA_NT1N/view?usp=drive_link).

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-
