### ISSUE TITLE
Configuraciones-->ABM Lista de precios: error al aplicar y deshacer varias veces el coeficiente

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#263]
Ambiente Test - v2.4.2

**Descripción:** _El coeficiente acumulativo_
Cuando se aplica por segunda vez el coeficiente en la misma lista de precios ocurre un error de cálculo del coeficiente, siendo superior al que le corresponde.
**Nota:** si se refresca la pantalla realiza los cálculos correctamente. 

https://github.com/user-attachments/assets/40e198dd-d396-4794-bc9e-5e6324fb45b4

**Pasos a reproducir:**

1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Elegir una lista de precios
4. Clic en el botón de acción "Nueva versión"
5. Ingresar un Nro en el campo "coeficiente"
6. Clic en el botón "Aplicar"
7. Clic en el botón "Guardar"
8. Elegir la misma lista de precios del paso 3) y continuar hasta el paso 6)
9. Observar si el cálculo es correcto

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.4
