### ISSUE TITLE
Configuraciones-->ABM Lista de precios: falla al agregar más de 10 artículos & adaptar el modal que permita scrollear

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#264]
Ambiente Test - v2.4.3

**Descripción:**
Cuando se agregan de forma gradual más de 10 artículos a una lista de precios el sistema solo recupera 10 artículos. Lo adecuado sería que muestre todos registros que se agregan. Sospecho que esto sucede en el front, pero en la base de datos están guardados los registros correctamente.

https://github.com/user-attachments/assets/f068ea90-b0cc-47a1-b1b2-1ed19052ea39

**Nota:** en el caso de no visualizarse el video completo se deja el link del [video](https://drive.google.com/file/d/1b4aoIOPfTkdcDiw27DuoXxLlEk9DwzOA/view?usp=drive_link)

**Pasos a reproducir:**

1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Elegir una lista de precios
4. Clic en el botón de acción "Nueva versión"
5. Clic en el botón "Seleccionar artículo"
6. Clic en el botón "Agregar"
7. Clic en el botón "Guardar"   
8. Repetir pasos 6 y 7 ý superar la cantidad de 10 artículos

---

### Mejora 
Un tema no menos importante que se observa en el video es que al intentar visualizar todo listado de artlículos el modal se traba y no se pueden ver todos los registros. 
**Resultado esperado:** Que el sistema permita escrollear sobre el modal para poder ver los datos de la ventana de forma completa.

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.4
