### ISSUE TITLE
Dnato: falla al ingresar con usuario creado por el cliente

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#266]
Ambiente Producción - v2.4.3

**Descripciión:**
Al intentar intenta ingresar con el usuario el sistema muestra el siguiente error y sin poder ingresar, pavor de corregir para que el cliente pueda acceder con dicho usuario: almacenlama@tierracapayan.com.ar

![image](https://github.com/user-attachments/assets/255b0c6d-8d46-4f7d-87b6-d1840a71b294)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en PROD.
