### ISSUE TITLE
ARMO-->Configuraciones-->ABM Lista de precios: falla al agregar más de 10 artículos & adaptar el modal que permita scrollear

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#268]
Ambiente Test - v2.4.5

**Descripción:**
En una nueva lista de precios cuando se agregan más de 10 artículos el sistema recupera 5 artículos. Lo adecuado sería que muestre todos registros que se agregan. 

En el caso de "Lista de Cumbres" se han agregado cerca de 15 artículos y al consultar desde el botón de acción se observa que solo recupera 5

![image](https://github.com/user-attachments/assets/570eed85-2bb3-4fa0-8621-9dcc2aff4843)

**Pasos a reproducir:**

1. En el menú Configuraciones
2. Clic en ABM Lista de precios
3. Clic en el botón "Agregar"
4. Clic en el botón "Seleccionar artículo"
5. Clic en el botón "Agregar" (agregar más de 10 artículos)
6. Clic en el botón "Guardar"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.3
