### ISSUE TITLE
Gestión de Usuarios --> error del link de la opción "Roles"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#30]
**Descripción:**
Al clickear sobre la lista desplegable del botón "Gestión de Usuarios" el link redirecciona a otra pantalla que se encuentra inhabilitada, sería conveniente que muestre la pantalla nueva del botón "Roles"

https://user-images.githubusercontent.com/88331456/139309229-1a6efdd5-cf25-48d3-8a0c-e9d42c314324.mp4

![LoCorrecto](https://user-images.githubusercontent.com/88331456/139310075-6e73fc10-c067-4e05-857c-9bf4ea6b640a.png)

**Pasos para la reproducción:**

1. Dar click sobre el botón desplegable de la esquina superior derecha 
2. Dar click en el botón de "Usuario"
3. Clickear sobre el botón desplegable "Gestión de Usuarios"
4. Dar click en opción: "Roles"

**Comment by aalfaro-trazalog** [comment]
Actualización 10/1 v 1.5.33.2
Desde gestión de usuarios ya no aparece el botón de roles. Ahora sólo se puede acceder a esta funcionalidad desde el botón  "Rol" que aparece en el listado.

![image](https://user-images.githubusercontent.com/87376576/148785498-fbc53ab5-7c7a-4105-a9b1-1102a9126be0.png)
