### ISSUE TITLE
Configuración -->Establecimientos: el sistema marca error al Editar un dato y no guarda la edición 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#37]
Ambiente: Test

**Descripción:**
Al editar algún/os dato/s de un Establecimiento seleccionado y presionar el botón "Guardar" el sistema muestra un cartel que dice "Error agregando Establecimiento" y al refrescar la página tampoco se guarda el cambio. 
**Sugerencia:** 
Quizá lo adecuado sería que abra una modal preguntando si desea realizar dicha edición y de ser afirmativa guardar el cambio

https://user-images.githubusercontent.com/88331456/142423991-b5d191e8-de34-42e4-a824-5e0fbebb55cd.mp4

**Pasos para la reproducción:**

1. En el menú "Configuración"
2. Dar click sobre el botón de acción "Editar"
3. Realizar el cambio y clickear sobre el botón "Guardar"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.35
