### ISSUE TITLE
Usuarios-->Gestión de Usuarios-->Agregar: salta error #500

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#44]
Ambiente test1 - v1.5.31

**Descripción:**
Al dar clic en la opción "Agregar usuario" el sistema se redirecciona a HTTP ERROR 500 

![Captur12-23](https://user-images.githubusercontent.com/88331456/147247563-5b0a58de-e599-4336-b7ca-9ffdaef5ff43.png)

**Pasos a reproducir:**

1. En el botón de perfil (parte superior derecha de la pantalla)
2. Clic en el botón de "Usuarios"
3. Clic en "Gestión de Usuarios"
4. Clic en "Agregar Usuario"

**Comment by aalfaro-trazalog** [comment]
Actualización 10/1
Ahora salta error apenas se presiona el botón de "usuarios"
https://user-images.githubusercontent.com/87376576/148768415-ecbbdeaa-b767-4646-b9c3-4ea95880ca72.mp4
