### ISSUE TITLE
Tools--> Gestión de Usuarios: Cambio de Rol, falta seleccionables

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#48]
v 1.5.33.2

Descripción:
Para poder realizar el Cambio de Rol, es necesario agregar el listado de los roles al select

![image](https://user-images.githubusercontent.com/87376576/148834521-05f7451a-11e5-4d68-a472-bd047788ebeb.png)

**Comment by floto-trazalog** [comment]
Solucionado. 
Al redireccionar la base de datos TEST a la base de ambiente de producción
