### ISSUE TITLE
Menú --> Agrandar margen de la caja desplegable

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#51]
v 1.5.35

Descripción:

Al desplegar el menú de Pañol y Producción falta margen para que el texto pueda leerse correctamente.

![image](https://user-images.githubusercontent.com/87376576/152812305-8b0fd0d8-4402-41f2-b91f-511205989672.png)

![image](https://user-images.githubusercontent.com/87376576/152812445-1db81490-c336-4515-8bc7-1fa4b8e8629a.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1
