### ISSUE TITLE
Lista de Usuarios: error de fechas último login

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#56]
v 1.5.36

**Descripción:**
El último login de los diferentes usuarios no se corresponde en fecha ni hora.

![image](https://user-images.githubusercontent.com/87376576/153891096-280a17b1-a285-4268-aad3-c25a027ac0a4.png)

**Pasos para reproducir:**
1. Seleccionar icono de usuario (desde perfil admin)
2. Click en usuario
3. Listado de usuarios

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.10
