### ISSUE TITLE
Menú--> Producción: Cambiar nombre de rec no consumible

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#58]
v 1.5.37

Descripción:
Cambiar el nombre del submenú rec no consumible a "Desocupar no consumible"

![image](https://user-images.githubusercontent.com/87376576/155217330-b68dbd2d-25a4-4681-8015-d41b04fef675.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.10
