### ISSUE TITLE
Configuración--> Clientes: revisar como muestra la escritura del tipo cliente

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#67]
ambiente PROD v2.0.3

Descripción:
Al crear un nuevo cliente, el sistema muestra el nombre como esta asociado a la lista de valores, no tal cual se lo ingreso. En este caso el tipo de cliente es "Industrial" y aparece como "tipos_clientesIndustrial"

![image](https://user-images.githubusercontent.com/87376576/157704382-cb76dfe6-c5f2-431d-930d-7715cdac4cd9.png)

**Comment by floto-trazalog** [comment]
Solucionado antes de v2.3.11
