### ISSUE TITLE
Dnato--> Agregar roles, no permite realizar multiselect

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#77]
v 2.0.10.7

Descripción:
Cuando se edita el rol de un usuario, si se le quiere agregar nuevos roles de forma múltiple, aparece el cartel de guardado exitoso pero no se guarda correctamente, es decir solo deja ingresar de a un rol. Además, el sistema no muestra alert de error.

https://user-images.githubusercontent.com/87376576/166247641-ff33d598-79e6-4ddf-a94a-62023b4b5cc8.mp4

Nota: desde el back se puede observar los siguiente errores:
EBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #URL >> http://10.142.0.16:8280/tools/bpm/users/german@yudica.com/session/X-Bonita-API-Token%3D7e2dbb6d-2261-4571-809e-d2b55144a75d%3BJSE     SSIONID%3DD82EE7AD27E388E1624433D7BE30BA07%3Bbonita.tenant%3D1%3B
2884 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HEADER SALIDA >> GET /tools/bpm/users/german@yudica.com/session/X-Bonita-API-Token%3D7e2dbb6d-2261-4571-809e-d2b55144a75d%3BJSESSIONID%3     DD82EE7AD27E388E1624433D7BE30BA07%3Bbonita.tenant%3D1%3B HTTP/1.1^M
2885 Host: 10.142.0.16:8280^M
2886 Accept: */*^M
2887 ^M
2888 
2889 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HTTP_CODE >> 404
2890 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HEADER RESPUESTA>> HTTP/1.1 404 Not Found^M
2891 Date: Mon, 02 May 2022 13:40:17 GMT^M
2892 Transfer-Encoding: chunked^M
2893 ^M
2894 
2895 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #BODY >> false
2896 ERROR - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HTTP_CODE >> 404
2897 ERROR - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HEADER RESPUESTA>> HTTP/1.1 404 Not Found^M
2898 Date: Mon, 02 May 2022 13:40:17 GMT^M
2899 Transfer-Encoding: chunked^M
2900 ^M
2901 
2902 ERROR - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #BODY >> false
2903 DEBUG - 2022-05-02 10:40:17 --> #TRAZA|ROLES|guardarMembershipBPM($membershipBPM, $userNick): $info_bpm >> null
2904 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #URL >> http://10.142.0.16:8280/tools/bpm/memberships
2905 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #PAYLOAD >> {"session":"\"X-Bonita-API-Token=658fcd51-ef8b-48c3-9606-1d89a88cf3e5;JSESSIONID=BCDEA4A05749709F4DFBDCBB58A527E8;bonita.tena     nt=1;\"","payload":{"user_id":null,"group_id":"407","role_id":"503"}}
2906 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HEADER SALIDA >> POST /tools/bpm/memberships HTTP/1.1^M
2907 Host: 10.142.0.16:8280^M
2908 Accept: */*^M
2909 Content-Type: application/json^M
2910 Content-Length: 194^M
2911 ^M
2912 
2913 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HTTP_CODE >> 404
2914 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HEADER RESPUESTA>> HTTP/1.1 404 Not Found^M
2915 Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate^M
2916 Content-Type: application/json; charset=UTF-8^M
2917 Date: Mon, 02 May 2022 13:40:17 GMT^M
2918 Transfer-Encoding: chunked^M
2919 ^M
2920 
2921 DEBUG - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #BODY >> "{\"respuesta\" : {\r                       \"codigo\" : \"1000\"  , \"error\":\"Error al invocar al BPM, verifique si esta disp     onible\"  , \"detalle\":\"\"  ,\"payload\":\"{\"exception\":\"class java.lang.NullPointerException\",\"message\":\"\"}\"           }\r}"
2922 ERROR - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HTTP_CODE >> 404
2923 ERROR - 2022-05-02 10:40:17 --> #TRAZA | #REST | #CURL | #HEADER RESPUESTA>> HTTP/1.1 404 Not Found^M
2924 Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate^M
2925 Content-Type: application/json; charset=UTF-8^M
2926 Date: Mon, 02 May 2022 13:40:17 GMT^M
2927 Transfer-Encoding: chunked^M

**Comment by floto-trazalog** [comment]
Solucionado en v1.2.12.1
