### ISSUE TITLE
Tareas-->Pedidos Trabajo: No se puede guardar

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-tools#8]
**Descripción:**
No es posible guardar un Nuevo Pedido de Trabajo en ambiente Test. Además no es posible seleccionar una Dirección de Entrega.

**Pasos para reproducir:**
1. En menú seleccionar "Tareas" y dar click en "Pedidos de Trabajo"
2. Dentro del Listado de Pedido Trabajo, dar click en el botón "Agregar"
3. Rellenar los campos requeridos
4. Click en botón "Guardar"

https://user-images.githubusercontent.com/87376576/130521936-6b103899-49b8-413d-ac0f-0f01ffb62021.mp4

**Comment by aalfaro-trazalog** [comment]
@lbgarcia  en ambiente Yudica esta funcionando, pero en Test1

**Comment by floto-trazalog** [comment]
Solucionado en la v2.0.16
