### ISSUE TITLE
Configuración-->ABM Transportista: al agregar no registra el nuevo transportista 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-tools#87]
Actualización
URGENTE para ambiente PROD - Millenium v2.1.3
---------------------------------------------------------------------------------------------------------------------
Ambiente test - v2.0.13.6

**Descripción:**
Al agregar transportista abre el cartel de guardado exitoso y no registra el guardado

https://user-images.githubusercontent.com/88331456/171276518-4cc2416e-00fe-4ccb-987a-438fb4126f37.mp4

**Pasos a seguir:**

1. En Configuración
2. Clic en ABM Transportistas
3. Clic en el botón "Agregar"

**Comment by gramos-trazalog** [comment]
Se modificaron en COREDataService las siguientes queries:
setClientes
getClientexEmpresayEstado

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.10
